"""
For this challenge, we know the values of A, g and p. But we don't know a and b.
a is generated by Alice and b is generated by Bob.

B = we supply the value of B equals to p, because that way s will become 0
s = pow(B, a, p)
key = s.to_bytes(256, "little")[:16]

cipher = AES.new(key=key, mode=AES.MODE_CBC)
flag = open("/flag", "rb").read()
ciphertext = cipher.iv + cipher.encrypt(pad(flag, cipher.block_size))
print(f"Flag Ciphertext (hex): {ciphertext.hex()}")

We don't know the AES key, the challenge is using to encrypt. So we will try to generate
s, such that AES key becomes predictable and we can use our own code to decrypt.

"""

import secrets
from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad

p_hex = "0xffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a08798e3404ddef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7edee386bfb5a899fa5ae9f24117c4b1fe649286651ece45b3dc2007cb8a163bf0598da48361c55d39a69163fa8fd24cf5f83655d23dca3ad961c62f356208552bb9ed529077096966d670c354e4abc9804f1746c08ca18217c32905e462e36ce3be39e772c180e86039b2783a2ec07a28fb5c55df06f4c52c9de2bcbf6955817183995497cea956ae515d2261898fa051015728e5a8aacaa68ffffffffffffffff"

a_hex = "0x94eec25b6c4d4db8ff1e17169cf67a1764a1f0cc3cbe72e24078cc134cf9e1d7cac9a48e53024ee606b7347e76f7c535b3b8205035996d4a63fcb616c7fd9b4f33a7e40e907a0e29d7a55f46896aeb20c210bc65462fe05569e6f306c1bf98fe8fadb7582c1b5384a008a4929176e52016b60d12de39c9de4ba95fac178af85523b401bac4a4dbce5caa8b1cb70937390ab2489b1ffa03df0975c50752520e78fc8fdec7759ebba31bc751f4c27f5aa10d0696ef845d4b6e57e639e11bd8e2f910a7839a4813d54a5b3378171100ea6163428b5df04b1b862e2499a935b3ebb72a0f5b3ed4447083a53e9a157d53bdcf82788a623ff2d6aeb30865b45bb2c86b"

g_hex = "0x2"

p = int(p_hex, 16)
g = int(g_hex, 16)
A = int(a_hex, 16)

b = secrets.randbelow(p - 2) + 1

B = pow(g, b, p)
s = 0

print("B:", format(B, "x"))
print("shared secret:", format(s, "x"))

aes_key = s.to_bytes(256, "little")[:16]

ct = bytes.fromhex(input("Cipher text hex? "))
aes_key = bytes.fromhex(aes_key.hex())

iv = ct[:16]
ciphertext = ct[16:]

cipher = AES.new(aes_key, AES.MODE_CBC, iv)
pt = unpad(cipher.decrypt(ciphertext), AES.block_size)
print("Message:", pt.decode("ascii"))
